CREATE TABLE `STUDENT` (
	`SID` INT NOT NULL AUTO_INCREMENT,
	`RACE` varchar(250),
	`GENDER` char(1) NOT NULL,
	`DEPARTMENT` varchar(250),
	`MAJOR` varchar(250),
	`NAME` varchar(250) NOT NULL,
	`USERNAME` varchar(250) NOT NULL UNIQUE,
	`PASSWORD` varchar(1000) NOT NULL,
	`EMAIL` varchar(250) NOT NULL UNIQUE,
	`CITIZENSHIP` varchar(250) NOT NULL,
	`YEAR` varchar(250),
	PRIMARY KEY (`SID`)
);

CREATE TABLE `ADMIN` (
	`AID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(250) NOT NULL,
	`USERNAME` varchar(250) NOT NULL UNIQUE,
	`PASSWORD` varchar(1000) NOT NULL,
	`EMAIL` varchar(250) NOT NULL UNIQUE,
	PRIMARY KEY (`AID`)
);

CREATE TABLE `EVENT` (
	`EID` INT NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` varchar(1000),
	`NAME` varchar(250) NOT NULL,
	`DATE_FROM` DATETIME NOT NULL,
	`DATE_TO` DATETIME NOT NULL,
	`EVENT_TYPE` varchar(250) NOT NULL,
	`MODALITY` varchar(250) NOT NULL,
	`LOCATION` varchar(500) NOT NULL,
	`E_AID` INT NOT NULL,
	PRIMARY KEY (`EID`)
);

CREATE TABLE `INVITED_TO` (
	`I_SID` INT NOT NULL,
	`I_EID` INT NOT NULL,
	`ATTENDING` varchar(3),
	PRIMARY KEY (`I_SID`,`I_EID`)
);

CREATE TABLE `PROVIDES_FEEDBACK` (
	`P_SID` INT NOT NULL,
	`P_EID` INT NOT NULL,
	`FEEDBACK` varchar(1000) NOT NULL,
	PRIMARY KEY (`P_SID`,`P_EID`)
);

ALTER TABLE `EVENT` ADD CONSTRAINT `EVENT_fk0` FOREIGN KEY (`E_AID`) REFERENCES `ADMIN`(`AID`);

ALTER TABLE `INVITED_TO` ADD CONSTRAINT `INVITED_TO_fk0` FOREIGN KEY (`I_SID`) REFERENCES `STUDENT`(`SID`);

ALTER TABLE `INVITED_TO` ADD CONSTRAINT `INVITED_TO_fk1` FOREIGN KEY (`I_EID`) REFERENCES `EVENT`(`EID`);

ALTER TABLE `PROVIDES_FEEDBACK` ADD CONSTRAINT `PROVIDES_FEEDBACK_fk0` FOREIGN KEY (`P_SID`) REFERENCES `STUDENT`(`SID`);

ALTER TABLE `PROVIDES_FEEDBACK` ADD CONSTRAINT `PROVIDES_FEEDBACK_fk1` FOREIGN KEY (`P_EID`) REFERENCES `EVENT`(`EID`);






